// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import models "github.com/king-jam/gotd/pkg/api/models"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Latest provides a mock function with given fields: ctx
func (_m *Service) Latest(ctx context.Context) (*models.GIF, error) {
	ret := _m.Called(ctx)

	var r0 *models.GIF
	if rf, ok := ret.Get(0).(func(context.Context) *models.GIF); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GIF)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, _a1
func (_m *Service) Set(ctx context.Context, _a1 *models.GIF) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GIF) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
